M48
; DRILL file {KiCad (7.0.0-0)} date Monday, 13. March 2023 at 16:32:39
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-13T16:32:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X56.48Y-73.0
X57.75Y-24.74
X108.55Y-39.98
X108.55Y-67.92
T0
M30
