M48
; DRILL file {KiCad (7.0.0-0)} date Sunday, 23. April 2023 at 15:23:40
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-23T15:23:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X56.462Y-72.9
X57.732Y-24.64
X108.532Y-39.88
X108.532Y-67.82
T0
M30
